Implement detect-fsd-root, generate-files, is-typescript-in-project
feature-sliced/cli pull request #5
Opened 2023-10-14 19:47 UTC by AgentRBY

Closes #2, #3, #4

-------

Тесты ещё не добавлены и, если честно, я без понятия как мне файловую систему тестировать :)
Я пробовал смотреть на `fs-mock`, но он у меня почему-то не завёлся. Если у просматривающих есть какие-то варианты как тестировать это, то буду рад услышать совет :)
Из-за тестов PR пока-что оставил в draft. 

Так же хочу предложить улучшения по спецификации: 
\- неплохо было бы сделать определение fsd-root не только на текущем cwd и выше, а ещё и проверяя `cwd`/src, потому-что частый кейс, когда люди в корне проекта запускают cli, а у них весь основной код в src лежит :)
\- добавить флаг который позволит вручную указывать использовать .ts или .js

2023-10-14 20:30 UTC, illright requested changes
Привет, спасибо, что взялся! Можешь, пожалуйста, оставить комментарии в этих ишьюс, что ты за них взялся? Иначе не могу тебя заассайнить на них

Насчет тестов — тоже сходу не скажу, как, думал, что можно создать просто несколько тестовых "проектов" (просто папочная структура, без наполнения) в папке `specs/mocks` и потестировать на них, запуская из разных папок вокруг этих "проектов".

Заметил, что ты взялся за три задачи сразу. Это круто, и задачи, в целом, достаточно ограниченные по скоупу, но я вижу несколько проблем с этим:
1. Тебе в счет хактоберфеста пойдет только 1 ПР
2. Мне чуть менее удобно ревьюить :)
3. Покрытие тестами — более требовательная подзадача, и хотелось бы уделить каждой из исходных задач внимание по покрытию тестами
4. Ты написал `Closes #2, #3, #4`, а гитхабу нужно, чтоб ты написал `Closes #2, closes #3, closes #4`

Но это не блокер, можем и в одном ПРе продолжить, если тебе так удобнее. Еще раз спасибо, код ты написал классно

2023-10-14 20:30 UTC, illright commented on src/detect-fsd-root.ts
> +  while (currentPath !== path.resolve(currentPath, "..")) {
Сорри, что не очень явно это сказал, но я в спеке имел в виду искать FSD-руты не в родительских папках, а в дочерних. Т.е., двигаться BFS-ом по папкам в CWD. Тут, наверное, стоит сделать явное исключение для `node_modules`, но по-хорошему, наверное, найти бы рут гит-репозитория и прочитать гит-игнор файл.

Это также к твоему предложению искать еще `${cwd}/src`

2023-10-14 20:30 UTC, illright commented on src/generate-files.ts
> +  const workingDirectory = path.resolve(fsdRoot);
nitpick (non-blocking): по задаче это должен быть уже абсолютный путь, можно это пропустить

2023-10-14 20:30 UTC, illright commented on src/generate-files.ts
> +      recursive: true,
suggestion: кажется, тут можно и не recursive

2023-10-14 20:30 UTC, illright commented on src/generate-files.ts
> +  const workingDirectory = path.resolve(fsdRoot);
issue: но надо еще учесть, что в `request` есть поле `rootOverride`, которое должно взять верх над переданным через аргумент `fsdRoot` полем. Идея в том, что `fsdRoot` вычисляется автоматически, а `request.rootOverride` предоставляется пользователем

2023-10-14 20:30 UTC, illright commented on src/generate-files.ts
> +      if (!layerFiles.includes(slice)) {
issue: тут немного другая история, потому что `slice` — не обязательно одна папка, это может быть вложенные папки типа `"group/slice-name"`. 

suggestion: поэтому тут можно обойтись без этой проверки и оставить recursive: true

2023-10-14 20:30 UTC, illright commented on src/generate-files.ts
> +            await fs.mkdir(segmentPath, { recursive: true });
ну а тут можно без recursive, думаю

2023-10-14 20:32 UTC, illright commented
Насчет флага, позволяющего указывать TS или JS — я не могу придумать практических юзкейсов, когда система детектинга TS выдаст не тот результат, которого хочет пользователь. У тебя есть примеры, когда это может понадобиться?

2023-10-14 20:53 UTC, AgentRBY commented
Комментарии в тасках оставил

> Покрытие тестами — более требовательная подзадача, и хотелось бы уделить каждой из исходных задач внимание по покрытию тестами

Я буду стараться покрывать все возможные кейсы в тестах всех функций. Но все ещё остаётся проблемой их написание в целом, так как создавать для каждого отдельного теста директорию как-то не очень, потому-что тестов может быть много. Плюс, `generate-files` создаёт файлы и я не уверен, поддерживает ли CI гитхаба такое. Я ещё покопаю в эту сторону, может смогу поднять `mock-fs` или найти альтернативу

> Ты написал Closes #2, #3, #4, а гитхабу нужно, чтоб ты написал Closes #2, closes #3, closes #4

Нет, гитхаб и так все понимает, можешь сам посмотреть в таски :)

-----

Фидбек по коду гляну уже завтра

2023-10-15 20:40 UTC, AgentRBY commented on src/generate-files.ts
> +  const workingDirectory = path.resolve(fsdRoot);
Я считаю, что это не ответственность generate-files выбирать какой рут ему использовать. Думаю, лучше что бы эта функция основывалась на fsdRoot, а там уже при её вызове выбирать какой рут - request.rootOverride или что-то другое

2023-10-15 20:44 UTC, AgentRBY commented on src/generate-files.ts
> +            await fs.mkdir(segmentPath, { recursive: true });
В теории, можно было бы и без recursive, но с ним получается возможность создавать вложенные сегменты. Если не делать recursive, то оно упадёт с ошибкой при вложенных сегментах, а значит придётся её обрабатывать, да и UX станет хуже - все таки, может кому-то да понадобиться создавать вложенные сегменты.

2023-10-15 20:46 UTC, AgentRBY commented
> Насчет флага, позволяющего указывать TS или JS — я не могу придумать практических юзкейсов, когда система детектинга TS выдаст не тот результат, которого хочет пользователь. У тебя есть примеры, когда это может понадобиться?

На практике я не видел таких случаев, но в теории человек может вынести tsconfig.json куда-нибудь типа config/tsconfig.json (и пути к нему в компиляторах вручную выставлять), и тогда текущая система детектинга TS не сработает :)

2023-10-16 20:01 UTC, illright commented on src/detect-fsd-root.ts
> +  ".vscode",
[suggestion (non-blocking)](https://conventionalcomments.org/): может быть, эти папки не игнорировать? Они обычно всего пару файлов содержат, так что замедлять выполнение не будут, но если мы их тут оставим, я переживаю, что это будет прецедентом добавлять сюда и другие маленькие папки, и этот список разрастется

2023-10-16 20:01 UTC, illright commented on src/detect-fsd-root.ts
> +      ? await filterIgnoredFolders(directories)
[question](https://conventionalcomments.org/): а нам разве не нужно здесь передать еще `currentDirectory`?

2023-10-16 20:02 UTC, illright commented on src/generate-files.ts
> +  const workingDirectory = path.resolve(fsdRoot);
А, блин, я тут осознал, что если юзер передает `rootOverride`, то нам даже не надо запускать алгоритм поиска рута. Окей, зря быканул

2023-10-17 14:31 UTC, AgentRBY commented on src/detect-fsd-root.ts
> +      ? await filterIgnoredFolders(directories)
Текущая дериктория и так фильтруется перед тем как добавиться в queue, так что её там не должно быть

2023-10-17 15:37 UTC, illright commented on src/detect-fsd-root.ts
> +      ? await filterIgnoredFolders(directories)
Я не об этом, я к тому, что `directories` — это, вроде бы, список просто имен, не резолвнутых путей

2023-10-17 15:40 UTC, AgentRBY commented on src/detect-fsd-root.ts
> +      ? await filterIgnoredFolders(directories)
Да, понял, позже исправлю

2023-10-19 15:52 UTC, illright commented
Немного не уверен насчёт проверок `.endsWith`, так мы можем поймать папки, которые не должны были быть пойманы, например, `flat-pages`. Мб заюзать [`path.basename`](https://stackoverflow.com/a/19811573/5726823)?

2023-10-19 20:56 UTC, illright reviewed
Окей, кажется, всё хорошо. Есть идеи по тестам?

2023-10-19 20:56 UTC, illright commented on src/detect-fsd-root.ts
> +    layers.some((ignored) => path.basename(file) === ignored),
suggestion (non-blocking):
```suggestion
    layers.includes(path.basename(file)),
```

2023-10-20 21:25 UTC, AgentRBY commented
> Окей, кажется, всё хорошо. Есть идеи по тестам?

Уже на выходных буду смотреть по тестам. Посмотрю сначала fs-mock, если не смогу поднять, то буду пробовать идею с папками. Если CI гитхаба умеет создавать папки, то можно их на лету генерировать, проверять, а потом удалять и так для каждого теста отдельно. Если нет, то печально, ведь у нас как минимум есть generate-files который надо тоже тестировать, поэтому я полюбому буду пытаться поднять fs-mock

2023-10-28 09:43 UTC, AgentRBY commented
Наконец-то дошли руки до тестов. Вроде все сделал, все работает, но есть одна проблема - вообще без понятия как тестировать все, что связано с `simple-git`, так как его нельзя ни замокать, ни эмулировать гит в `mockFs` (`simpleGit().init()` создаст реальную папку на диске, так как он просто вызывает команду "git init", а не использует fs). Поэтому пока без него закомитил.

2023-10-28 17:21 UTC, illright requested changes
praise: Суперское покрытие тестами, особенно с `mock-fs` очень удачно получилось

issue: одна блокирующая проблема — кажется, ты забыл добавить `mock-fs` в `devDependencies`, из-за них сейчас тесты не ранятся) После этого можем вливать, в целом, насчет остальных комментариев — они все не блокеры, если хочешь, поправь, если не хочешь — забей

Спасибо еще раз за качественную работу. Обязательно отметим тебя в ридмишке как со-автора.

2023-10-28 17:21 UTC, illright commented on package.json
> +    "simple-git": "^3.20.0",
suggestion (non-blocking): давай перенесем это в `dependencies`, всё-таки, в рантайме используется

2023-10-28 17:21 UTC, illright commented on src/is-typescript-in-project.ts
> +export async function isPathContainsItem(
nitpick (non-blocking): хочется переименовать в `pathContainsItem`, т.к. иначе получается два глагола — _is_ и _contains_

2023-10-28 17:21 UTC, illright commented on src/specs/generate-files.spec.ts
> +  test("create multiple segments", async () => {
issue (non-blocking): тут, кажется, немного неточное описание, я бы ожидал, что _create multiple segments_ — это про создание `ui` и `api` в одном слайсе

suggestion: 
```suggestion
  test("create multiple slices with the same segment", async () => {
```

2023-10-28 17:21 UTC, illright commented on src/specs/generate-files.spec.ts
> +  test("create multiple segments", async () => {
suggestion (non-blocking): и хотелось бы тогда также добавить такой тест, где создается один слайс, и в нем несколько сегментов

2023-10-28 17:21 UTC, illright commented on src/detect-fsd-root.ts
> +export async function getLayersCountInFolder(
suggestion (non-blocking): может, не экспортировать эти функции, `getLayersCountInFolder` и `filterIgnoredFolders`? Чтоб поддерживать консистентность того, что в файле `detect-fsd-root.ts` главный и единственный экспорт — функция `detectFsdRoot`

2023-10-28 17:21 UTC, illright commented on src/specs/detect-fsd-root.spec.ts
> +  test("2 layers in child dir, 3 layers in second child dir, should ignore second folder", async () => {
issue (non-blocking): описание предписывает три слоя в игнорируемой папке, а в тесте две

suggestion: поскольку разницы тут особо нет, давай просто исправим описание теста
```suggestion
  test("2 layers in child dir, 2 layers in second child dir, should ignore second folder", async () => {
```

2023-10-28 17:23 UTC, illright commented
Ах да — насчет тестирования гита — забей, покроем интеграционными тестами. Если тебе интересно написать их — дай знать, но лучше бы уже в другом ПРе, чтоб этот не блокировать

2023-10-28 18:24 UTC, AgentRBY commented on src/detect-fsd-root.ts
> +export async function getLayersCountInFolder(
В целом можно, но тогда тесты для них придётся удалить, ведь доступ к этим функциям не получить

2023-10-28 19:26 UTC, illright commented on src/detect-fsd-root.ts
> +export async function getLayersCountInFolder(
а, точно, чето не подумал

2023-10-30 11:51 UTC, AgentRBY commented
Вроде весь фидбек сделал. Меняю статус PR на Ready For Review, можно мёрджить

Если будет время, займусь самим cli, если, конечно, его до этого не сделают

2023-10-30 12:09 UTC, illright approved these changes

2023-10-30 12:10 UTC, merged